### ISSUE TITLE
Баг-трекер

### ISSUE THREAD

**Issue by astyled** [Wondermarin/vdark#40]
Не совсем понимаю, зачем он был добавлен в исключения. Всяко лучше увидеть мелкие недочёты, чем светлую тему посреди ночи.
Но я решил сам поковырять код, сюда скинуть (не уверен, что на гитхабе предложения по коду в ошибки надо постить):
```
.bt_report_title_link {
     font-weight: 700;
      -webkit-font-smoothing: antialiased;
     color: #ddd;
     font-size: 13px;
    }
    
    .bt_reports_found {
    font-weight: 500;
    -webkit-font-smoothing: subpixel-antialiased;
    color: #aaa;
    font-size: 13px;
    position: relative;
    box-sizing: border-box;
    width: 100%;
    padding: 20px 5px 5px;
    margin: 0px -15px 0px 0px;
}

.bt_report_info {
    color: #aaa;
    font-size: 12px;
}

.bt_tag_label {
    color: #000;
    display: inline-block;
    font-size: 12.5px;
    line-height: 12.5px;
    vertical-align: top;
    border-radius: 3px;
    padding: 5px 9px 4px;
    background: #ccc;
}
```

Как переделать `.no_rows` (инфа про устройства) я не разобрался
`a` (которая #fff и имя человека) решил не менять т.к. не знаю почему оно уже так отмечено.

Это было предложение. А вот баг: сами страницы багов в исключения не попадают и поэтому выглядят плохо. Там тоже что-то поменял:
```
.bt_report_footer {
    border-top: 1px solid #e7e8ec;
    padding: 11px 20px 11px;
    background: #212121;
    white-space: nowrap;
}

.bt_report_one_info_row_label {
    color: #d1d1d1;
    float: left;
    width: 230px;
}

.bt_report_one_descr>h3 {
    color: #eee;
    font-size: 12px;
    font-weight: 500;
    -webkit-font-smoothing: subpixel-antialiased;
    -moz-osx-font-smoothing: auto;
    margin: 12px 0 8px;
}

.bt_comment_form_unavailable {
    padding: 35px 75px;
    text-align: center;
    background: #212121;
    color: #ddd;
    line-height: 160%;
}
```
Не знаю как изменить `.box_controls .flat_button.secondary, .flat_button.secondary.button_light`
ну и других мелких недочётов остаётся много. Я их исправить не могу т.к. в теме всяких вебов и css разбираюсь плохо.

**Comment by astyled** [comment]
Скриншоты

Было:
![image](https://user-images.githubusercontent.com/42794343/81961887-6bd3ee00-962c-11ea-90fd-d5eb17d75fe6.png)
(
![image](https://user-images.githubusercontent.com/42794343/81962034-9625ab80-962c-11ea-95f0-3edceb6b7cd9.png)
)
![image](https://user-images.githubusercontent.com/42794343/81961928-755d5600-962c-11ea-9ee2-7978bacd6f92.png)
Стало:
![image](https://user-images.githubusercontent.com/42794343/81961774-4646e480-962c-11ea-96cd-c2ac757ecf61.png)
![image](https://user-images.githubusercontent.com/42794343/81961795-5068e300-962c-11ea-81a2-6eac1661c080.png)

**Comment by Wondermarin** [comment]
Да, его стоит вернуть.
