### ISSUE TITLE
Всё ещё крестики

### ISSUE THREAD

**Issue by Mioryy** [Wondermarin/vdark#44]
Установил всё последней версии, но крестик всё ещё остался.
![image](https://user-images.githubusercontent.com/67579518/85988398-00898400-ba00-11ea-8a5b-e14de762ca97.png)

**Comment by Wondermarin** [comment]
Скорее всего вы используете тему с userstyles.org, эта ошибка наблюдается только там.
Воспользуйтесь шагами по установке с файла readme.md
